services:
  db:
    image: postgres:16
    container_name: taskmanager
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager
      POSTGRES_DB: taskmanager
    volumes:
      - taskmanager_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  taskmanager_data:

networks:
  app-net:
    name: app-net
    driver: bridge
